const Answers = [
    { testId: 'PracticeTest1', questionNum: 1, attrib: 'Diction', answer: 'D'},
    { testId: 'PracticeTest1', questionNum: 2, attrib: 'Add/Delete/Revise', answer: 'B'},
    { testId: 'PracticeTest1', questionNum: 3, attrib: 'Apostrophe with none', answer: 'A'},
    { testId: 'PracticeTest1', questionNum: 4, attrib: 'Comma, Semicolon, Colon', answer: 'C'},
    { testId: 'PracticeTest1', questionNum: 5, attrib: 'Sentence order', answer: 'C'},
    { testId: 'PracticeTest1', questionNum: 6, attrib: 'Add/Delete/Revise', answer: 'D'},
    { testId: 'PracticeTest1', questionNum: 7, attrib: 'Idiom/preposition', answer: 'B'},
    { testId: 'PracticeTest1', questionNum: 8, attrib: 'Parallel structure', answer: 'C'},
    { testId: 'PracticeTest1', questionNum: 9, attrib: 'Transition', answer: 'A'},
    { testId: 'PracticeTest1', questionNum: 10, attrib: 'Diction', answer: 'A'},
    { testId: 'PracticeTest1', questionNum: 11, attrib: 'Comma splice', answer: 'B'},
    { testId: 'PracticeTest1', questionNum: 12, attrib: 'Infographic', answer: 'B'},
    { testId: 'PracticeTest1', questionNum: 13, attrib: 'FANBOYS', answer: 'A'},
    { testId: 'PracticeTest1', questionNum: 14, attrib: 'Transition', answer: 'B'},
    { testId: 'PracticeTest1', questionNum: 15, attrib: 'Commas', answer: 'C'},
    { testId: 'PracticeTest1', questionNum: 16, attrib: 'Colon', answer: 'C'},
    { testId: 'PracticeTest1', questionNum: 17, attrib: 'Comma Splice', answer: 'C'},
    { testId: 'PracticeTest1', questionNum: 18, attrib: 'Tense', answer: 'A'},
    { testId: 'PracticeTest1', questionNum: 19, attrib: 'Its their, there', answer: 'D'},
    { testId: 'PracticeTest1', questionNum: 20, attrib: 'Add/Delete/Revise', answer: 'D'},
    { testId: 'PracticeTest1', questionNum: 21, attrib: 'Shorter is better', answer: 'B'},
    { testId: 'PracticeTest1', questionNum: 22, attrib: 'Sentence order', answer: 'D'},
    { testId: 'PracticeTest1', questionNum: 23, attrib: 'Shorter is better', answer: 'D'},
    { testId: 'PracticeTest1', questionNum: 24, attrib: 'Dangling modifier', answer: 'D'},
    { testId: 'PracticeTest1', questionNum: 25, attrib: 'Idiom/preposition', answer: 'B'},
    { testId: 'PracticeTest1', questionNum: 26, attrib: 'Colon', answer: 'A'},
    { testId: 'PracticeTest1', questionNum: 27, attrib: 'Transition', answer: 'B'},
    { testId: 'PracticeTest1', questionNum: 28, attrib: 'Add/Delete/Revise', answer: 'C'},
    { testId: 'PracticeTest1', questionNum: 29, attrib: 'Infographic', answer: 'B'},
    { testId: 'PracticeTest1', questionNum: 30, attrib: 'Who vs whom', answer: 'D'},
    { testId: 'PracticeTest1', questionNum: 31, attrib: 'Sentence order', answer: 'C'},
    { testId: 'PracticeTest1', questionNum: 32, attrib: 'Colon', answer: 'A'},
    { testId: 'PracticeTest1', questionNum: 33, attrib: 'Register, diction', answer: 'A'},
    { testId: 'PracticeTest1', questionNum: 34, attrib: 'Transition', answer: 'A'},
    { testId: 'PracticeTest1', questionNum: 35, attrib: 'Shorter is better', answer: 'A'},
    { testId: 'PracticeTest1', questionNum: 36, attrib: 'Sentence vs Fragment', answer: 'B'},
    { testId: 'PracticeTest1', questionNum: 37, attrib: 'Add/Delete/Revise', answer: 'D'},
    { testId: 'PracticeTest1', questionNum: 38, attrib: 'Transition', answer: 'C'},
    { testId: 'PracticeTest1', questionNum: 39, attrib: 'Combining sentences', answer: 'A'},
    { testId: 'PracticeTest1', questionNum: 40, attrib: 'Subject-verb agreement', answer: 'B'},
    { testId: 'PracticeTest1', questionNum: 41, attrib: 'Apostrophe', answer: 'B'},
    { testId: 'PracticeTest1', questionNum: 42, attrib: 'Add/Delete/Revise', answer: 'C'},
    { testId: 'PracticeTest1', questionNum: 43, attrib: 'Sentence vs Fragment', answer: 'D'},
    { testId: 'PracticeTest1', questionNum: 44, attrib: 'Pronoun Agreement', answer: 'D'},
];

module.exports = Answers;